name: build deploy dev site

on:
  push:
    branches: [dev]

jobs:
  build-deploy-dev-site:

    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: poktlint.com
          push: false

      - name: Run image
        id: docker_run
        uses: addnab/docker-run-action@v3
        with:
          image: poktlint.com
          options: -v ${{ github.workspace }}/build:/app/build -w /app/build
          run: yarn run build

      - name: Deploy dev.poktlint.com
        id: docker_run_deploy_dev_poktlint_com
        uses: addnab/docker-run-action@v3
        with:
          image: amazon/aws-cli
          options: -v ${{ github.workspace }}:/workspace -e AWS_REGION=us-east-1 -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: aws s3 sync /workspace/build s3://dev.poktlint.com --acl public-read --delete
